#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Review_Project
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_SocialReview")]
	public partial class DB_SocialReviewDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPRODUCER_ACCOUNT(PRODUCER_ACCOUNT instance);
    partial void UpdatePRODUCER_ACCOUNT(PRODUCER_ACCOUNT instance);
    partial void DeletePRODUCER_ACCOUNT(PRODUCER_ACCOUNT instance);
    partial void InsertREVIEWER_ACCOUNT(REVIEWER_ACCOUNT instance);
    partial void UpdateREVIEWER_ACCOUNT(REVIEWER_ACCOUNT instance);
    partial void DeleteREVIEWER_ACCOUNT(REVIEWER_ACCOUNT instance);
    partial void InsertPRODUCT_CATEGORY(PRODUCT_CATEGORY instance);
    partial void UpdatePRODUCT_CATEGORY(PRODUCT_CATEGORY instance);
    partial void DeletePRODUCT_CATEGORY(PRODUCT_CATEGORY instance);
    #endregion
		
		public DB_SocialReviewDataContext() : 
				base(global::Review_Project.Properties.Settings.Default.DB_SocialReviewConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_SocialReviewDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_SocialReviewDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_SocialReviewDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_SocialReviewDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PRODUCER_ACCOUNT> PRODUCER_ACCOUNTs
		{
			get
			{
				return this.GetTable<PRODUCER_ACCOUNT>();
			}
		}
		
		public System.Data.Linq.Table<REVIEWER_ACCOUNT> REVIEWER_ACCOUNTs
		{
			get
			{
				return this.GetTable<REVIEWER_ACCOUNT>();
			}
		}
		
		public System.Data.Linq.Table<PRODUCT_CATEGORY> PRODUCT_CATEGORies
		{
			get
			{
				return this.GetTable<PRODUCT_CATEGORY>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUCER_ACCOUNT")]
	public partial class PRODUCER_ACCOUNT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _USERID;
		
		private string _USERNAME;
		
		private string _USERPASS;
		
		private string _GMAIL;
		
		private string _PHONE;
		
		private System.Nullable<System.DateTime> _DATE_CREATED;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUSERIDChanging(string value);
    partial void OnUSERIDChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnUSERPASSChanging(string value);
    partial void OnUSERPASSChanged();
    partial void OnGMAILChanging(string value);
    partial void OnGMAILChanged();
    partial void OnPHONEChanging(string value);
    partial void OnPHONEChanged();
    partial void OnDATE_CREATEDChanging(System.Nullable<System.DateTime> value);
    partial void OnDATE_CREATEDChanged();
    #endregion
		
		public PRODUCER_ACCOUNT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this.OnUSERIDChanging(value);
					this.SendPropertyChanging();
					this._USERID = value;
					this.SendPropertyChanged("USERID");
					this.OnUSERIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERPASS", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string USERPASS
		{
			get
			{
				return this._USERPASS;
			}
			set
			{
				if ((this._USERPASS != value))
				{
					this.OnUSERPASSChanging(value);
					this.SendPropertyChanging();
					this._USERPASS = value;
					this.SendPropertyChanged("USERPASS");
					this.OnUSERPASSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GMAIL", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string GMAIL
		{
			get
			{
				return this._GMAIL;
			}
			set
			{
				if ((this._GMAIL != value))
				{
					this.OnGMAILChanging(value);
					this.SendPropertyChanging();
					this._GMAIL = value;
					this.SendPropertyChanged("GMAIL");
					this.OnGMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string PHONE
		{
			get
			{
				return this._PHONE;
			}
			set
			{
				if ((this._PHONE != value))
				{
					this.OnPHONEChanging(value);
					this.SendPropertyChanging();
					this._PHONE = value;
					this.SendPropertyChanged("PHONE");
					this.OnPHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_CREATED", DbType="Date")]
		public System.Nullable<System.DateTime> DATE_CREATED
		{
			get
			{
				return this._DATE_CREATED;
			}
			set
			{
				if ((this._DATE_CREATED != value))
				{
					this.OnDATE_CREATEDChanging(value);
					this.SendPropertyChanging();
					this._DATE_CREATED = value;
					this.SendPropertyChanged("DATE_CREATED");
					this.OnDATE_CREATEDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.REVIEWER_ACCOUNT")]
	public partial class REVIEWER_ACCOUNT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _USERID;
		
		private string _USERNAME;
		
		private string _USERPASS;
		
		private string _GMAIL;
		
		private string _PHONE;
		
		private System.Nullable<System.DateTime> _DATE_CREATED;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUSERIDChanging(string value);
    partial void OnUSERIDChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnUSERPASSChanging(string value);
    partial void OnUSERPASSChanged();
    partial void OnGMAILChanging(string value);
    partial void OnGMAILChanged();
    partial void OnPHONEChanging(string value);
    partial void OnPHONEChanged();
    partial void OnDATE_CREATEDChanging(System.Nullable<System.DateTime> value);
    partial void OnDATE_CREATEDChanged();
    #endregion
		
		public REVIEWER_ACCOUNT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="VarChar(40)")]
		public string USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this.OnUSERIDChanging(value);
					this.SendPropertyChanging();
					this._USERID = value;
					this.SendPropertyChanged("USERID");
					this.OnUSERIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERPASS", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string USERPASS
		{
			get
			{
				return this._USERPASS;
			}
			set
			{
				if ((this._USERPASS != value))
				{
					this.OnUSERPASSChanging(value);
					this.SendPropertyChanging();
					this._USERPASS = value;
					this.SendPropertyChanged("USERPASS");
					this.OnUSERPASSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GMAIL", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string GMAIL
		{
			get
			{
				return this._GMAIL;
			}
			set
			{
				if ((this._GMAIL != value))
				{
					this.OnGMAILChanging(value);
					this.SendPropertyChanging();
					this._GMAIL = value;
					this.SendPropertyChanged("GMAIL");
					this.OnGMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string PHONE
		{
			get
			{
				return this._PHONE;
			}
			set
			{
				if ((this._PHONE != value))
				{
					this.OnPHONEChanging(value);
					this.SendPropertyChanging();
					this._PHONE = value;
					this.SendPropertyChanged("PHONE");
					this.OnPHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_CREATED", DbType="Date")]
		public System.Nullable<System.DateTime> DATE_CREATED
		{
			get
			{
				return this._DATE_CREATED;
			}
			set
			{
				if ((this._DATE_CREATED != value))
				{
					this.OnDATE_CREATEDChanging(value);
					this.SendPropertyChanging();
					this._DATE_CREATED = value;
					this.SendPropertyChanged("DATE_CREATED");
					this.OnDATE_CREATEDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUCT_CATEGORY")]
	public partial class PRODUCT_CATEGORY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CATEGORY_NAME;
		
		private string _CATEGORY_CODE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCATEGORY_NAMEChanging(string value);
    partial void OnCATEGORY_NAMEChanged();
    partial void OnCATEGORY_CODEChanging(string value);
    partial void OnCATEGORY_CODEChanged();
    #endregion
		
		public PRODUCT_CATEGORY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORY_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CATEGORY_NAME
		{
			get
			{
				return this._CATEGORY_NAME;
			}
			set
			{
				if ((this._CATEGORY_NAME != value))
				{
					this.OnCATEGORY_NAMEChanging(value);
					this.SendPropertyChanging();
					this._CATEGORY_NAME = value;
					this.SendPropertyChanged("CATEGORY_NAME");
					this.OnCATEGORY_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORY_CODE", DbType="VarChar(10)")]
		public string CATEGORY_CODE
		{
			get
			{
				return this._CATEGORY_CODE;
			}
			set
			{
				if ((this._CATEGORY_CODE != value))
				{
					this.OnCATEGORY_CODEChanging(value);
					this.SendPropertyChanging();
					this._CATEGORY_CODE = value;
					this.SendPropertyChanged("CATEGORY_CODE");
					this.OnCATEGORY_CODEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
