<?xml version="1.0" encoding="utf-8"?><Database Name="DB_SocialReview" Class="DB_SocialReviewDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-8R396UP\SQLEXPRESS;Initial Catalog=DB_SocialReview;Integrated Security=True" SettingsObjectName="Review_Project.Properties.Settings" SettingsPropertyName="DB_SocialReviewConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PRODUCER_ACCOUNT" Member="PRODUCER_ACCOUNTs">
    <Type Name="PRODUCER_ACCOUNT">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USERID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="USERPASS" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="GMAIL" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="DATE_CREATED" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.REVIEWER_ACCOUNT" Member="REVIEWER_ACCOUNTs">
    <Type Name="REVIEWER_ACCOUNT">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USERID" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="USERPASS" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="GMAIL" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="DATE_CREATED" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUCT_CATEGORY" Member="PRODUCT_CATEGORies">
    <Type Name="PRODUCT_CATEGORY">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CATEGORY_NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CATEGORY_CODE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>